repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: mixed-line-ending
    args:
    - --fix=lf

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
  - id: isort
    args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --use-parentheses
    - --line-width=88

- repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
  hooks:
  - id: pylint
    args:
    - --max-line-length=88

- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
