name: Run tests

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Add Poetry to path
      run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
    - name: Install yupi on venv
      run: poetry install
    - name: Run pre-commit checks
      run: poetry run pre-commit run --all-files
    - name: Run tests
      run: poetry run pytest ./tests/
